apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: demo 
  labels:
    app: demo-api

spec:
  replicas: 2

  selector: 
    matchLabels:
      app: demo-api
      
  template:
    metadata:
      labels:
        app: demo-api

    spec:
      serviceAccountName: demo-api-sa
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      
      containers:
        - name: demo-api
          image: acrsecuritylab29791.azurecr.io/demo-api@sha256:2c04b0a4b18c778e99c26041511bb2638ff923aeadaa5b6d9c66a0849a28d06f

          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          envFrom:
            - configMapRef:
                name: demo-api-config

          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {} 