apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: demo
  name: demo-api-read-binding

subjects:
  - kind: ServiceAccount
    name: demo-api-sa
    namespace: demo

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demo-api-reader

