name: create-aks

on:
  workflow_dispatch:


permissions:
  contents: read
  id-token: write

concurrency:
  group: aks-sec-lab
  cancel-in-progress: false

env:
  RESOURCE_GROUP: rg-aks-sec-lab
  LOCATION: polandcentral
  AKS_NAME: aks-sec-lab
  NODE_COUNT: 2
  NODE_VM_SIZE: Standard_B2s_v2

jobs:
    create-aks:
        runs-on: ubuntu-latest
        name: Create AKS Cluster
        environment: dev

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Log via OIDC to Azure
              uses: azure/login@v3
              with:
                client-id: ${{ vars.AZURE_CLIENT_ID }}
                tenant-id: ${{ vars.AZURE_TENANT_ID }}
                subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
                

            - name: Conduct checks
              id: checks
              run: |
                if az aks show \
                    --resource-group ${{ env.RESOURCE_GROUP }} \
                    --name ${{ env.AKS_NAME }}; then
                  echo "aks_exists=true" >> $GITHUB_OUTPUT

                else
                  echo "aks_exists=false" >> $GITHUB_OUTPUT
                fi

            - name: Create AKS if doesn't exist
              run: |
                if [ "${{ steps.checks.outputs.aks_exists }}" = "true" ]; then
                  echo "AKS ${{ env.AKS_NAME}} exists. Step skiped"
                else
                  echo "AKS doesn't exist and will be deployed"

                  az aks create \
                    --resource-group ${{ env.RESOURCE_GROUP }} \
                    --name ${{ env.AKS_NAME }} \
                    --location ${{ env.LOCATION }} \
                    --node-count ${{ env.NODE_COUNT }} \
                    --node-vm-size ${{ env.NODE_VM_SIZE}} \
                    --enable-managed-identity \
                    --enable-aad \
                    --enable-azure-rbac \
                    --network-plugin azure \
                    --network-plugin-mode overlay \
                    --generate-ssh-keys \
                    --only-show-errors
                fi
            
            - name: Attache ACR to AKS
              run: |
                  az aks update \
                      --resource-group ${{ env.RESOURCE_GROUP }} \
                      --name ${{ env.AKS_NAME }} \
                      --attach-acr ${{ vars.ACR_NAME_SHORT }} \
                      --only-show-errors

            - name: Verify kublet identity
              run: |
                  az aks show \
                      --resource-group ${{ env.RESOURCE_GROUP }} \
                      --name ${{ env.AKS_NAME }} \
                      --query "identityProfile.kubeletIdentity" \
                      --only-show-errors

            - name: Enable AKS Addons
              run: |
                  az aks addon enable \
                      --resource-group ${{ env.RESOURCE_GROUP }} \
                      --name ${{ env.AKS_NAME }} \
                      --addon azure-policy \
                      --only-show-errors

            - name: Ensure AKS Cluster Admin role for GitHub OIDC identity
              shell: bash
              run: |
                SP_OBJECT_ID=$(az ad sp show \
                  --id "${{ vars.AZURE_CLIENT_ID }}" \
                  --query id \
                  --output tsv)

                ROLE_SCOPE=$(az group show \
                    --name "$RESOURCE_GROUP" \
                    --query id \
                    --output tsv)

                EXISTING_ASSIGNMENT=$(az role assignment list \
                  --assignee-object-id "$SP_OBJECT_ID" \
                  --scope "$ROLE_SCOPE" \
                  --role "Azure Kubernetes Service RBAC Cluster Admin" \
                  --query "length(@)" \
                  --output tsv)

                if [ "$EXISTING_ASSIGNMENT" = "0" ]; then
                  echo "Assigning AKS RBAC Cluster Admin to GitHub OIDC identity."

                  az role assignment create \
                    --assignee-object-id "$SP_OBJECT_ID" \
                    --assignee-principal-type ServicePrincipal \
                    --role "Azure Kubernetes Service RBAC Cluster Admin" \
                    --scope "$ROLE_SCOPE"
                else
                  echo "AKS RBAC Cluster Admin role assignment already exists."
                fi