name: create-aks

on:
  workflow_dispatch:


permissions:
  contents: read
  id-token: write

concurrency:
  group: aks-sec-lab
  cancel-in-progress: false

env:
  RESOURCE_GROUP: rg-aks-sec-lab
  LOCATION: polandcentral
  AKS_NAME: aks-sec-lab

jobs:
    create-aks:
        runs-on: ubuntu-latest
        name: Create AKS Cluster
        environment: dev

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Log via OIDC to Azure
              uses: azure/login@v3
              with:
                client-id: ${{ vars.AZURE_CLIENT_ID }}
                tenant-id: ${{ vars.AZURE_TENANT_ID }}
                subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

            - name: Conduct checks
              id: checks
              run: |
                if az aks show \
                    --resource-group ${{ env.RESOURCE_GROUP }} \
                    --name ${{ env.AKS_NAME }}; then
                  echo "aks_exists=true" >> $GITHUB_OUTPUT
                else
                  echo "aks_exists=false" >> $GITHUB_OUTPUT
                fi

            - name: Create AKS if doesn't exist
              run: |
                if [ "${{ steps.checks.outputs.aks_exists }}" = "true" ]; then
                  echo "AKS exists. Step skiped"
                else
                  echo "AKS doesn't exist and be deployed"
                fi