name: enable-cilium

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

env:
    RESOURCE_GROUP: rg-aks-sec-lab
    AKS_NAME: aks-sec-lab

jobs:
    enable-cilium: 
        runs-on: ubuntu-latest
        environment: dev

        steps:
            - name: Checkout code
              uses: actions/checkout@v7

            - name: Log via OIDC to Azure
              uses: azure/login@v3
              with:
                client-id: ${{ vars.AZURE_CLIENT_ID }}
                tenant-id: ${{ vars.AZURE_TENANT_ID }}
                subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

            - name: Show current network configuration
              run: |
                az aks show \
                    --resource-group "$RESOURCE_GROUP" \
                    --name "$AKS_NAME" \
                    --query 'networkProfile' \
                    --output json

            - name: Enable Azure CNI Powered by Cilium
              run: | 
                az aks update \
                    --resource-group "$RESOURCE_GROUP" \
                    --name "$AKS_NAME" \
                    --network-dataplane cilium \
                    --network-policy cilium \
                    --only-show-errors

            - name: Verify Cillium Dataplane
              run: |
                az aks show \
                    --resource-group "$RESOURCE_GROUP" \
                    --name "$AKS_NAME" \
                    --query '{
                    networkPlugin:networkProfile.networkPlugin,
                    networkPluginMode:networkProfile.networkPluginMode,
                    networkDataplane:networkProfile.networkDataplane,
                    networkPolicy:networkProfile.networkPolicy,
                    provisioningState:provisioningState,
                    }' \
                    --output json